### ISSUE TITLE
Campfires timeline activity display issue

### ISSUE THREAD

**Issue by infinity899** [PeerMeHQ/issues#1]
- Platform (Web, App, ...):
Any
- Platform Version (v#.#.#):
Any
- Operating System and Version (MacOS, Windows, iOS, Android, ...):
Any
- Browser (Chrome, Firefox, Safari, ...): #.#
Any

### Description:
Activity for campfires displayed in PeerID timeline shows campfire message with unformatted space characters.
![image](https://user-images.githubusercontent.com/27764573/219589026-0bdfa0c9-527d-4343-bc48-a73e47b82148.png)

**Comment by michavie** [comment]
Looks like something when wrong stripping the markup - moved it the roadmap board 👍

**Comment by michavie** [comment]
should be fixed on devnet - feel free to reopen
