### ISSUE TITLE
Campfires textarea caret bug

### ISSUE THREAD

**Issue by infinity899** [PeerMeHQ/issues#2]
- Platform (Web, App, ...):
All
- Platform Version (v#.#.#):
All
- Operating System and Version (MacOS, Windows, iOS, Android, ...):
All
- Browser (Chrome, Firefox, Safari, ...): #.#
All

### Description:
In the text area of a campfire when replying or creating a new one there is a bug when you want to edit/change something in the middle of your sentence. The caret always jumps to the last character.

### Detailed steps to reproduce the issue:
Go to campfires
Reply in a campfire
Try editing/adding a new word in the middle of your sentence
Caret will jump and write the word at the end of the sentence

Attaching video submitted  by a peer

https://user-images.githubusercontent.com/27764573/222345264-cb11b544-2bca-47ed-ab78-4781a0844a45.MOV

**Comment by michavie** [comment]
should be fixed on devnet - feel free to reopen

**Comment by infinity899** [comment]
Tested on dev & main: **fixed**
